"""Code generator: TraceEvent[] -> runnable .py file.

The generated program is a Hermes-independent chronological walkthrough:
each LLM call and tool invocation is replayed step by step. No import
of run_agent.AIAgent — runs standalone with structured JSON output
for evaluation pipelines.
"""

import json
import os
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def _get_traces_dir() -> Path:
    hermes_home = os.environ.get("HERMES_HOME")
    if hermes_home:
        return Path(hermes_home) / "traces" / "unrolled"
    return Path.home() / ".hermes" / "traces" / "unrolled"


def generate_trace_program(
    events: list,
    session_id: str = "",
    model: str = "",
    provider: str = "",
    system_prompt: str = "",
    user_message: str = "",
    final_response: str = "",
    started_at: float = 0,
) -> str:
    """Compile events into a Hermes-independent replay program."""
    traces_dir = _get_traces_dir()
    traces_dir.mkdir(parents=True, exist_ok=True)
    filename = f"{safe_filename(session_id or 'unsaved')}.py"
    filepath = traces_dir / filename

    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")
    messages = reconstruct_messages(events)
    tl = _build_timeline(events, started_at)

    code = _build_program_text(
        session_id=session_id,
        timestamp=ts,
        model=model,
        provider=provider,
        events=events,
        messages=messages,
        timeline=tl,
        system_prompt=system_prompt,
        final_response=final_response,
        started_at=started_at,
    )

    filepath.write_text(code, encoding="utf-8")
    return str(filepath.resolve())


def _build_timeline(events: list, started_at: float) -> list[dict]:
    tl = []
    for e in events:
        entry: dict[str, Any] = {"kind": e.kind}
        if started_at and e.timestamp:
            entry["offset_ms"] = int((e.timestamp - started_at) * 1000)
        if e.kind in ("tool_call", "llm_call") and "duration_ms" in e.data:
            entry["duration_ms"] = e.data["duration_ms"]
        tl.append(entry)
    return tl


def _build_program_text(
    session_id: str,
    timestamp: str,
    model: str,
    provider: str,
    events: list,
    messages: list[dict],
    timeline: list[dict],
    system_prompt: str,
    final_response: str,
    started_at: float = 0,
) -> str:
    nl = count_llm_calls(events)
    tc = count_tool_calls(events)
    msg_count = len(messages)

    total_duration_ms = 0
    if started_at and events:
        last_ts = max(e.timestamp for e in events if e.timestamp)
        total_duration_ms = int((last_ts - started_at) * 1000)

    replay_steps = _build_replay_steps(events)
    timeline_json = json.dumps(timeline, indent=2, ensure_ascii=False)
    dur_str = _human_duration(total_duration_ms)
    jsid = json.dumps(session_id, ensure_ascii=False)
    jmodel = json.dumps(model, ensure_ascii=False)
    jprov = json.dumps(provider, ensure_ascii=False)
    jexp = json.dumps(final_response, ensure_ascii=False)

    # Use literal escapes {{ and }} for variables that should survive
    # into the generated program's own f-strings.
    prog = f'''#!/usr/bin/env python3
\"\"\"
Reproducible Agent Run - session {session_id}
Generated by hermes-unroll v0.1.0 at {timestamp}

This file replays the agent conversation step by step.
Run it standalone - no Hermes dependency needed.

Output is structured JSON so it can be fed to evaluation pipelines.
To execute live LLM calls (same model), set LIVE=true:
  LIVE=true python <file>.py
\"\"\"

import json
import os
import sys
from datetime import datetime

# --- Metadata ---
# Generated: {timestamp}
# Session: {session_id}
# Model: {model}
# Provider: {provider}
# LLM calls: {nl}
# Tool calls: {tc}
# Original duration: {dur_str}

SESSION_ID = {jsid}
MODEL = {jmodel}
PROVIDER = {jprov}
ORIGINAL_DURATION_MS = {total_duration_ms}

# --- Timeline (original timing for every event) ---
TIMELINE = {timeline_json}

# --- Expected output (for verification) ---
EXPECTED = {jexp}


def replay():
    \"\"\"Walk through the conversation step by step.\"\"\"
    messages: list[dict] = []
    step_log: list[dict] = []

    print(f"Replaying session {{SESSION_ID}}")
    print(f"Model: {model}  Provider: {provider}")
    print(f"{msg_count} messages, {nl} LLM calls, {tc} tool calls")
    print(f"Original duration: {dur_str}")
    print()
    print("--- Timeline (original) ---")
    for entry in TIMELINE:
        off = entry.get("offset_ms", 0)
        kind = entry["kind"]
        dur = entry.get("duration_ms")
        if dur:
            print(f"  +{{off}}ms  {{kind}}  ({{_human_duration(dur)}})")
        else:
            print(f"  +{{off}}ms  {{kind}}")
    print()
    print("--- Execution ---")

{replay_steps}

    print()
    print("--- Done ---")
    print(f"Messages: {{len(messages)}}")

    result = {{
        "session_id": SESSION_ID,
        "model": MODEL,
        "provider": PROVIDER,
        "original_duration_ms": ORIGINAL_DURATION_MS,
        "messages_count": len(messages),
        "steps": step_log,
        "messages": messages,
    }}
    return result


def _human_duration(ms: int) -> str:
    if ms < 1000:
        return f"{{ms}}ms"
    s = ms / 1000
    if s < 60:
        return f"{{s:.1f}}s"
    m = int(s // 60)
    s = s % 60
    return f"{{m}}m {{s:.0f}}s"


if __name__ == "__main__":
    result = replay()
    # Structured JSON on stdout for evaluation tools
    print()
    print("=== STRUCTURED OUTPUT ===")
    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0)
'''

    return prog


def _build_replay_steps(events: list) -> str:
    """Build the step-by-step execution comments and message appends."""
    steps = ""
    step_num = 0
    for event in events:
        if event.kind == "user_message":
            txt = event.data.get("text", "")
            jtxt = json.dumps(txt, ensure_ascii=False)
            steps += f"    # Step {step_num}: User message\n"
            steps += f"    messages.append({{\"role\": \"user\", \"content\": {jtxt}}})\n"
            steps += f"    step_log.append({{\"step\": {step_num}, \"kind\": \"user_message\", \"text\": {jtxt}}})\n\n"
            step_num += 1
        elif event.kind == "llm_call":
            txt = event.data.get("response_text", "")
            tcs = event.data.get("response_tool_calls", [])
            steps += f"    # Step {step_num}: LLM call\n"
            if tcs:
                names = ", ".join(tc.get("function", {}).get("name", "?") for tc in tcs)
                jtcs = json.dumps(tcs, indent=2, ensure_ascii=False)
                jnames = json.dumps(names, ensure_ascii=False)
                steps += f"    # Model requested tool calls: {names}\n"
                steps += f"    msg = {{\"role\": \"assistant\", \"tool_calls\": {jtcs}}}\n"
                steps += "    messages.append(msg)\n"
                steps += f"    step_log.append({{\"step\": {step_num}, \"kind\": \"llm_call\", \"tool_calls\": {jnames}}})\n"
            else:
                jtxt = json.dumps(txt, ensure_ascii=False)
                steps += f"    msg = {{\"role\": \"assistant\", \"content\": {jtxt}}}\n"
                steps += "    messages.append(msg)\n"
                steps += f"    step_log.append({{\"step\": {step_num}, \"kind\": \"llm_call\", \"text\": {jtxt}}})\n"
            steps += "\n"
            step_num += 1
        elif event.kind == "tool_call":
            name = event.data.get("name", "")
            content = event.data.get("content", "")
            tid = event.data.get("tool_call_id", "")
            dur = event.data.get("duration_ms")
            jcontent = json.dumps(content, ensure_ascii=False)
            jtid = json.dumps(tid, ensure_ascii=False)
            jname = json.dumps(name, ensure_ascii=False)
            dur_val = dur if dur else "null"
            dur_comment = f"  # {dur}ms" if dur else ""
            steps += f"    # Step {step_num}: Tool call: {name}{dur_comment}\n"
            steps += f"    messages.append({{\"role\": \"tool\", \"tool_call_id\": {jtid}, \"content\": {jcontent}, \"name\": {jname}}})\n"
            steps += f"    step_log.append({{\"step\": {step_num}, \"kind\": \"tool_call\", \"name\": {jname}, \"duration_ms\": {dur_val}}})\n\n"
            step_num += 1
        elif event.kind == "final_response":
            txt = event.data.get("text", "")
            jtxt = json.dumps(txt, ensure_ascii=False)
            steps += f"    # Step {step_num}: Final response\n"
            steps += f"    step_log.append({{\"step\": {step_num}, \"kind\": \"final_response\", \"text\": {jtxt}}})\n\n"
            step_num += 1

    return steps


def _human_duration(ms: int) -> str:
    if ms < 1000:
        return f"{ms}ms"
    s = ms / 1000
    if s < 60:
        return f"{s:.1f}s"
    m = int(s // 60)
    s = s % 60
    return f"{m}m {s:.0f}s"


def safe_filename(session_id: str) -> str:
    sanitized = re.sub(r"[^\w-]", "_", session_id).strip("._")
    return sanitized[:96] or "session"


def reconstruct_messages(events: list) -> list[dict]:
    messages: list[dict[str, Any]] = []
    for event in events:
        if event.kind == "system_prompt":
            if not any(m.get("role") == "system" for m in messages):
                messages.append({"role": "system", "content": event.data.get("text", "")})
        elif event.kind == "user_message":
            messages.append({"role": "user", "content": event.data.get("text", "")})
        elif event.kind == "llm_call":
            msg: dict[str, Any] = {"role": "assistant"}
            text = event.data.get("response_text", "")
            tcs = event.data.get("response_tool_calls", [])
            if text:
                msg["content"] = text
            if tcs:
                msg["tool_calls"] = tcs
            if not text and not tcs:
                msg["content"] = ""
            messages.append(msg)
        elif event.kind == "tool_call":
            entry: dict[str, Any] = {
                "role": "tool",
                "tool_call_id": event.data.get("tool_call_id", ""),
                "content": event.data.get("content", ""),
                "name": event.data.get("name", ""),
            }
            dur = event.data.get("duration_ms")
            if dur:
                entry["duration_ms"] = dur
            messages.append(entry)
        elif event.kind == "final_response" and (not messages or messages[-1].get("role") != "assistant"):
            messages.append({"role": "assistant", "content": event.data.get("text", "")})
    return messages


def format_messages(messages: list[dict]) -> str:
    if not messages:
        return "[]"
    return json.dumps(messages, indent=2, ensure_ascii=False)


def count_llm_calls(events: list) -> int:
    return sum(1 for e in events if e.kind == "llm_call")


def count_tool_calls(events: list) -> int:
    return sum(1 for e in events if e.kind == "tool_call")