"""Code generator: TraceEvent[] -> runnable .py file.

Takes a list of TraceEvent objects and emits a self-contained
Python program that reproduces the conversation.
"""

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

TRACES_DIR = Path.home() / ".hermes" / "traces" / "unrolled"


def generate_trace_program(
    events: list,
    session_id: str = "",
    model: str = "",
    provider: str = "",
    system_prompt: str = "",
    user_message: str = "",
    final_response: str = "",
) -> str:
    """Compile events into a self-contained .py file.

    Returns the absolute path to the written file.
    """
    TRACES_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"{safe_filename(session_id or 'unsaved')}.py"
    filepath = TRACES_DIR / filename

    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S")
    messages = reconstruct_messages(events)

    code = _build_program_text(
        session_id=session_id,
        timestamp=timestamp,
        model=model,
        provider=provider,
        events=events,
        messages=messages,
    )

    filepath.write_text(code, encoding="utf-8")
    return str(filepath.resolve())


def _build_program_text(
    session_id: str,
    timestamp: str,
    model: str,
    provider: str,
    events: list,
    messages: list[dict],
) -> str:
    """Build the .py file content as a string."""
    nl = count_llm_calls(events)
    tc = count_tool_calls(events)
    msg_count = len(messages)

    parts: list[str] = []
    parts.append("#!/usr/bin/env python3")
    parts.append('"""')
    parts.append(f"Reproducible Agent Run \u2014 session {session_id}")
    parts.append(f"Generated by hermes-unroll v0.1.0 at {timestamp}")
    parts.append(f"Original: model={model}, provider={provider}, turns={len(events)}")
    parts.append('"""')
    parts.append("")
    parts.append("import json")
    parts.append("")
    parts.append("# \u2500\u2500 Metadata \u2500\u2500")
    parts.append(f"# Generated: {timestamp}")
    parts.append(f"# Session: {session_id}")
    parts.append(f"# Model: {model}")
    parts.append(f"# Provider: {provider}")
    parts.append(f"# LLM calls: {nl}")
    parts.append(f"# Tool calls: {tc}")
    parts.append(f"# Messages: {msg_count}")
    parts.append("")
    parts.append("# \u2500\u2500 Conversation History \u2500\u2500")
    parts.append(f"CONVERSATION_HISTORY = {format_messages(messages)}")
    parts.append("")
    parts.append("")
    parts.append('if __name__ == "__main__":')
    parts.append(f"    print(f\"hermes-unroll trace for session {session_id}\")")
    parts.append(f"    print(f\"{msg_count} messages, {nl} LLM calls, {tc} tool calls\")")
    parts.append('    print("Trace loaded successfully.")')
    parts.append("")

    return "\n".join(parts)


def safe_filename(session_id: str) -> str:
    """Collapse non-alphanumeric characters for safe filenames."""
    sanitized = re.sub(r"[^\w-]", "_", session_id).strip("._")
    return sanitized[:96] or "session"


def reconstruct_messages(events: list) -> list[dict]:
    """Walk the event list and reconstruct the message sequence.

    Returns a list of dicts with keys: role, content, tool_calls,
    tool_call_id, name.
    """
    messages: list[dict[str, Any]] = []
    for event in events:
        if event.kind == "system_prompt":
            if not any(m.get("role") == "system" for m in messages):
                messages.append({"role": "system", "content": event.data.get("text", "")})
        elif event.kind == "user_message":
            messages.append({"role": "user", "content": event.data.get("text", "")})
        elif event.kind == "llm_call":
            msg: dict[str, Any] = {"role": "assistant"}
            text = event.data.get("response_text", "")
            tool_calls_raw = event.data.get("response_tool_calls", [])
            if text:
                msg["content"] = text
            if tool_calls_raw:
                msg["tool_calls"] = tool_calls_raw
            if not text and not tool_calls_raw:
                msg["content"] = ""
            messages.append(msg)
        elif event.kind == "tool_call":
            messages.append({
                "role": "tool",
                "tool_call_id": event.data.get("tool_call_id", ""),
                "content": event.data.get("content", ""),
                "name": event.data.get("name", ""),
            })
        elif event.kind == "final_response" and (not messages or messages[-1].get("role") != "assistant"):
                messages.append({"role": "assistant", "content": event.data.get("text", "")})
    return messages


def format_messages(messages: list[dict]) -> str:
    """Pretty-format the messages list as a Python literal string."""
    if not messages:
        return "[]"
    return json.dumps(messages, indent=2, ensure_ascii=False)


def count_llm_calls(events: list) -> int:
    """Count LLM call events."""
    return sum(1 for e in events if e.kind == "llm_call")


def count_tool_calls(events: list) -> int:
    """Count tool call events."""
    return sum(1 for e in events if e.kind == "tool_call")